import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import './CommunityPage.css'

const categories={ALL:'전체',EXPERIENCE:'복용 경험',QUESTION:'질문',SIDE_EFFECT:'부작용 경험',INFO_REPORT:'정보 제보'}
const reasons={MISINFORMATION:'허위·부정확한 정보',DANGEROUS_ADVICE:'위험한 복용 권유',DRUG_SALE:'의약품 판매·나눔',ADVERTISEMENT:'광고',ABUSE:'욕설·괴롭힘',PRIVACY:'개인정보 노출',OTHER:'기타'}
const reportTargets={POST:'게시글',COMMENT:'댓글'}
const emptyForm={category:'EXPERIENCE',title:'',content:'',medicationId:'',medicationName:'',experienceDuration:'',ageGroup:'',purpose:'',occurrenceTiming:'',currentlyTaking:false}

async function api(url,options){const res=await fetch(url,options);const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||'요청을 처리하지 못했습니다.');return data}

export default function CommunityPage({user}){
  const [filters,setFilters]=useState({q:'',category:'ALL',sort:'LATEST',page:1})
  const [result,setResult]=useState({items:[],total:0,page:1,hasMore:false})
  const [selected,setSelected]=useState(null)
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState('')
  const [compose,setCompose]=useState(false)
  const [editingId,setEditingId]=useState(null)
  const [form,setForm]=useState(emptyForm)
  const [medQuery,setMedQuery]=useState('')
  const [meds,setMeds]=useState([])
  const [comment,setComment]=useState('')
  const [notice,setNotice]=useState('')
  const [reports,setReports]=useState([])
  const [infoReports,setInfoReports]=useState([])
  const isAdmin=user?.role==='ADMIN'
  const canWrite=Boolean(user?.userId)&&user?.username!=='demo'
  const query=useMemo(()=>new URLSearchParams({q:filters.q,category:filters.category==='ALL'?'':filters.category,sort:filters.sort,page:String(filters.page)}).toString(),[filters])

  async function load(){setLoading(true);setError('');try{setResult(await api('/api/community/posts?'+query))}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{let active=true;api('/api/community/posts?'+query).then(data=>{if(active)setResult(data)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[query])
  useEffect(()=>{if(medQuery.trim().length<1)return;const t=setTimeout(()=>api('/api/community/medications?q='+encodeURIComponent(medQuery)).then(setMeds).catch(()=>setMeds([])),250);return()=>clearTimeout(t)},[medQuery])
  async function openPost(id){try{setSelected(await api('/api/community/posts/'+id));setNotice('')}catch(e){setError(e.message)}}
  async function submitPost(e){e.preventDefault();try{const post=await api(editingId?'/api/community/posts/'+editingId:'/api/community/posts',{method:editingId?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setCompose(false);setEditingId(null);setForm(emptyForm);setMedQuery('');setNotice(editingId?'글을 수정했습니다.':'글을 등록했습니다.');await load();setSelected(post)}catch(e){setNotice(e.message)}}
  async function toggleHelpful(){try{const data=await api('/api/community/posts/'+selected.postId+'/helpful',{method:'POST'});setSelected(v=>({...v,helpfulByMe:data.active?1:0,helpfulCount:data.count}));setResult(v=>({...v,items:v.items.map(x=>x.postId===selected.postId?{...x,helpfulByMe:data.active?1:0,helpfulCount:data.count}:x)}))}catch(e){setNotice(e.message)}}
  async function submitComment(e){e.preventDefault();try{await api('/api/community/posts/'+selected.postId+'/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:comment})});setComment('');await openPost(selected.postId)}catch(e){setNotice(e.message)}}
  async function report(targetType,targetId){if(!canWrite){setNotice('로그인 후 신고할 수 있습니다.');return}const input=window.prompt('신고 사유를 적어주세요.\n작성한 내용은 관리자에게 전달됩니다.');if(input===null)return;const detail=input.trim();if(!detail){setNotice('신고 사유를 입력해주세요.');return}if(detail.length>500){setNotice('신고 사유는 500자 이내로 입력해주세요.');return}try{await api('/api/community/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType,targetId,reason:'OTHER',detail})});setNotice('신고가 접수되었습니다. 관리자 확인 후 처리됩니다.')}catch(e){setNotice(e.message)}}
  function editPost(){setEditingId(selected.postId);setForm({category:selected.category,title:selected.title,content:selected.content,medicationId:selected.medicationId||'',medicationName:selected.medicationName||'',experienceDuration:selected.experienceDuration||'',ageGroup:selected.ageGroup||'',purpose:selected.purpose||'',occurrenceTiming:selected.occurrenceTiming||'',currentlyTaking:Number(selected.currentlyTaking)===1});setMedQuery(selected.medicationName||'');setSelected(null);setCompose(true)}
  async function deletePost(){if(!window.confirm('이 글을 삭제할까요?'))return;try{await api('/api/community/posts/'+selected.postId,{method:'DELETE'});setSelected(null);setNotice('글을 삭제했습니다.');load()}catch(e){setNotice(e.message)}}
  async function deleteComment(id){if(!window.confirm('댓글을 삭제할까요?'))return;try{await api('/api/community/comments/'+id,{method:'DELETE'});openPost(selected.postId)}catch(e){setNotice(e.message)}}
  async function loadReports(){try{const [a,b]=await Promise.all([api('/api/community/admin/reports'),api('/api/community/admin/info-reports')]);setReports(a);setInfoReports(b)}catch(e){setNotice(e.message)}}
  async function moderatePost(id,status){try{await api('/api/community/admin/posts/'+id+'/status',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});setNotice('게시글 상태를 변경했습니다.');load();loadReports();if(selected?.postId===id)setSelected(null)}catch(e){setNotice(e.message)}}
  async function resolveReport(id,status){try{await api('/api/community/admin/reports/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,resolutionNote:''})});loadReports()}catch(e){setNotice(e.message)}}
  async function reviewInfo(id,status){try{await api('/api/community/admin/posts/'+id+'/review',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});setNotice('정보 제보 검토를 완료했습니다.');loadReports();load()}catch(e){setNotice(e.message)}}
  return <div className="community-page">
    <header className="community-header"><div><span className="section-meta-tag">MEDICATION COMMUNITY</span><h1 className="section-title">약 이야기</h1><p>공식 자료에 없는 복용 경험을 나누고, 필요한 약 정보를 함께 채워가요.</p></div><button className="community-primary" onClick={()=>{if(!canWrite){setNotice('로그인 후 글을 작성할 수 있습니다.');return}setEditingId(null);setForm(emptyForm);setMedQuery('');setMeds([]);setCompose(true)}}>경험·질문 작성</button></header>
    <section className="community-safety"><strong>공식 정보와 사용자 경험은 다릅니다.</strong><span>게시글은 개인의 경험이며 의학적 판단이나 처방을 대신하지 않습니다. 이상사례는 한국의약품안전관리원에 별도로 보고할 수 있어요.</span><a href="https://kaers.drugsafe.or.kr/kaers/report/EgovPubReportReg.do" target="_blank" rel="noreferrer">이상사례 공식 보고 ↗</a></section>
    {notice&&<p className="community-notice" role="status">{notice}</p>}
    <div className="community-toolbar"><form onSubmit={e=>{e.preventDefault();setFilters(v=>({...v,q:e.currentTarget.q.value,page:1}))}}><input name="q" defaultValue={filters.q} placeholder="약 이름, 성분, 경험 내용 검색"/><button>검색</button></form><select value={filters.sort} onChange={e=>setFilters(v=>({...v,sort:e.target.value,page:1}))}><option value="LATEST">최신순</option><option value="HELPFUL">도움순</option><option value="COMMENTS">댓글순</option></select></div>
    <div className="community-tabs">{Object.entries(categories).map(([key,label])=><button key={key} aria-pressed={filters.category===key} onClick={()=>setFilters(v=>({...v,category:key,page:1}))}>{label}</button>)}</div>
    <div className="community-layout"><main className="community-feed">
      <div className="community-count">게시글 <strong>{result.total}</strong>건</div>{loading&&<p>글을 불러오고 있어요…</p>}{error&&<p role="alert">{error}</p>}
      {!loading&&!result.items.length&&<div className="community-empty">아직 등록된 이야기가 없습니다. 첫 경험을 공유해보세요.</div>}
      {result.items.map(post=><article key={post.postId} className="community-card" onClick={()=>openPost(post.postId)}><div className="community-card-top"><span className={'community-type '+post.category}>{categories[post.category]}</span>{post.reviewStatus==='PENDING'&&<span className="community-review">관리자 검토 중</span>}<time>{post.createdAt}</time></div><h2>{post.title}</h2>{post.medicationName&&<button className="community-med" type="button">💊 {post.medicationName}</button>}<p>{post.summary}</p><footer><span>{post.authorName}</span><span>도움 {post.helpfulCount||0}</span><span>댓글 {post.commentCount||0}</span></footer></article>)}
      <div className="community-pagination"><button disabled={filters.page<=1} onClick={()=>setFilters(v=>({...v,page:v.page-1}))}>이전</button><span>{filters.page} 페이지</span><button disabled={!result.hasMore} onClick={()=>setFilters(v=>({...v,page:v.page+1}))}>다음</button></div>
    </main><aside className="community-side"><h3>안전한 약 이야기</h3><ul><li>효과와 부작용은 개인마다 달라요.</li><li>복용량 변경은 의료진과 상의하세요.</li><li>약 판매·교환·나눔은 금지됩니다.</li><li>처방전의 개인정보는 가려주세요.</li></ul><Link to="/chat">공식 DB 기반으로 질문하기 →</Link>{isAdmin&&<button className="community-admin-open" onClick={loadReports}>관리자 신고함 열기</button>}</aside></div>

    {compose&&<div className="community-modal" onMouseDown={()=>{setCompose(false);setEditingId(null)}}><form className="community-compose" onSubmit={submitPost} onMouseDown={e=>e.stopPropagation()}><header><div><span className="section-meta-tag">SHARE EXPERIENCE</span><h2>{editingId?'약 이야기 수정':'약 이야기 작성'}</h2></div><button type="button" onClick={()=>{setCompose(false);setEditingId(null)}}>×</button></header><label>글 유형<select value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value}))}>{Object.entries(categories).filter(([k])=>k!=='ALL').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>약 연결<span className="community-optional">선택</span><input value={medQuery} onChange={e=>{const value=e.target.value;setMedQuery(value);if(!value.trim())setMeds([]);setForm(v=>({...v,medicationId:'',medicationName:value}))}} placeholder="제품명을 검색하세요"/></label>{meds.length>0&&<ul className="community-med-results">{meds.map(m=><li key={m.medicationId}><button type="button" onClick={()=>{setForm(v=>({...v,medicationId:m.medicationId,medicationName:m.itemName}));setMedQuery(m.itemName);setMeds([])}}><strong>{m.itemName}</strong><span>{m.entpName}</span></button></li>)}</ul>}<div className="community-form-grid"><label>복용 기간<input value={form.experienceDuration} onChange={e=>setForm(v=>({...v,experienceDuration:e.target.value}))} placeholder="예: 2주"/></label><label>연령대<select value={form.ageGroup} onChange={e=>setForm(v=>({...v,ageGroup:e.target.value}))}><option value="">선택 안 함</option>{['10대 이하','20대','30대','40대','50대','60대 이상'].map(x=><option key={x}>{x}</option>)}</select></label><label>복용 목적<input value={form.purpose} onChange={e=>setForm(v=>({...v,purpose:e.target.value}))}/></label><label>발생 시점<input value={form.occurrenceTiming} onChange={e=>setForm(v=>({...v,occurrenceTiming:e.target.value}))} placeholder="예: 복용 3일 후"/></label></div><label>제목<input required maxLength="150" value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label>내용<textarea required maxLength="4000" rows="8" value={form.content} onChange={e=>setForm(v=>({...v,content:e.target.value}))} placeholder="복용량을 임의로 권하지 말고, 직접 경험한 사실을 구체적으로 적어주세요."/></label><label className="community-check"><input type="checkbox" checked={form.currentlyTaking} onChange={e=>setForm(v=>({...v,currentlyTaking:e.target.checked}))}/>현재 복용 중입니다</label><button className="community-primary">{editingId?'수정 완료':'등록하기'}</button></form></div>}

    {selected&&<div className="community-modal" onMouseDown={()=>setSelected(null)}><article className="community-detail" onMouseDown={e=>e.stopPropagation()}><button className="community-close" onClick={()=>setSelected(null)}>×</button><div className="community-card-top"><span className={'community-type '+selected.category}>{categories[selected.category]}</span><time>{selected.createdAt}</time></div><h2>{selected.title}</h2>{selected.medicationName&&<div className="community-official"><strong>연결된 공식 제품</strong><span>{selected.medicationName}</span><Link to={'/chat?medicationId='+encodeURIComponent(selected.medicationId||'')}>DB 정보 질문하기 →</Link></div>}<div className="community-meta">작성자 {selected.authorName}{selected.ageGroup&&<> · {selected.ageGroup}</>}{selected.experienceDuration&&<> · 복용 {selected.experienceDuration}</>}</div><p className="community-content">{selected.content}</p><div className="community-detail-actions"><button className={selected.helpfulByMe?'active':''} onClick={toggleHelpful}>도움됐어요 {selected.helpfulCount||0}</button><button onClick={()=>report('POST',selected.postId)}>신고</button>{Number(selected.authorId)===Number(user?.userId)&&<><button onClick={editPost}>수정</button><button onClick={deletePost}>삭제</button></>}{isAdmin&&<><button onClick={()=>moderatePost(selected.postId,'HIDDEN')}>관리자 숨김</button><button onClick={()=>moderatePost(selected.postId,'VISIBLE')}>복구</button></>}</div><section className="community-comments"><h3>댓글 {selected.comments?.length||0}</h3>{selected.comments?.map(c=><div className="community-comment" key={c.commentId}><strong>{c.authorName}</strong><time>{c.createdAt}</time><p>{c.content}</p><div className="community-comment-actions"><button onClick={()=>report('COMMENT',c.commentId)}>신고</button>{Number(c.authorId)===Number(user?.userId)&&<button onClick={()=>deleteComment(c.commentId)}>삭제</button>}</div></div>)}{canWrite?<form onSubmit={submitComment}><textarea required maxLength="1000" value={comment} onChange={e=>setComment(e.target.value)} placeholder="개인의 경험을 존중하며 답변해주세요."/><button>댓글 등록</button></form>:<p><Link to="/login?next=/community">로그인</Link> 후 댓글을 작성할 수 있습니다.</p>}</section></article></div>}

    {isAdmin&&(reports.length>0||infoReports.length>0)&&<section className="community-admin"><header><div><span className="section-meta-tag">관리자 전용</span><h2>커뮤니티 관리</h2></div><button onClick={()=>{setReports([]);setInfoReports([])}}>닫기</button></header>{infoReports.length>0&&<><h3>검토 대기 정보 제보</h3>{infoReports.map(r=><article key={'info-'+r.postId}><div><strong>{r.medicationName||'약 미지정'} · {r.title}</strong><span>{r.authorName} · {r.createdAt}</span><p>{r.content}</p></div><div><button onClick={()=>reviewInfo(r.postId,'APPROVED')}>확인 승인</button><button onClick={()=>reviewInfo(r.postId,'REJECTED')}>반려</button><button onClick={()=>openPost(r.postId)}>원문 보기</button></div></article>)}</>}{reports.length>0&&<><h3>사용자 신고</h3>{reports.map(r=><article key={r.reportId}><div><strong>{r.detail||reasons[r.reason]||'신고 사유 없음'}</strong><span>{reportTargets[r.targetType]||'신고 대상'} #{r.targetId} · 신고자 {r.reporterName} · {r.createdAt}</span><p><b>신고 대상 내용</b><br/>{r.targetSummary||'대상 내용 없음'}</p></div><div><button onClick={()=>r.targetType==='POST'&&moderatePost(r.targetId,'HIDDEN')}>게시글 숨김</button><button onClick={()=>resolveReport(r.reportId,'RESOLVED')}>처리 완료</button><button onClick={()=>resolveReport(r.reportId,'DISMISSED')}>기각</button></div></article>)}</>}</section>}
  </div>
}


